name: QASM Runner CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run local Aer tests
        run: pytest -v tests/test_qasm_runner_aer.py

      - name: Run IBM Runtime tests (if key available)
        env:
          IBM_API_KEY: ${{ secrets.IBM_API_KEY }}
        run: pytest -v tests/test_qasm_runner_ibm.py
